CREATE TABLE tb_payment (
                            payment_date DATE NOT NULL,
                            valor DECIMAL(19, 2),
                            id_payment BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            id_user BIGINT,
                            category VARCHAR(255) NOT NULL CHECK (category IN ('LEISURE', 'STUDIES', 'FOOD', 'HOUSING', 'TRANSPORT', 'TRIPS', 'HEALTH')),
                            description VARCHAR(255),
                            payment_method VARCHAR(255) NOT NULL CHECK (payment_method IN ('MONEY', 'PIX', 'DEBIT_CARD', 'CRED_CARD')),
                            status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'CANCELED')),
                            PRIMARY KEY (id_payment)
);


ALTER TABLE tb_payment
    ADD CONSTRAINT FK_TB_PAYMENT_ON_ID_USER FOREIGN KEY (id_user) REFERENCES tb_user (id_user);