CREATE TABLE tb_user
(
    id_user  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id_user)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_username UNIQUE (username);