DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'tb_payment') THEN
    ELSE
        CREATE TABLE tb_payment (
                                    id_payment     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    description    VARCHAR(255),
                                    payment_date   DATE,
                                    value          DECIMAL(19, 2),
                                    category       VARCHAR(255),
                                    status         VARCHAR(255),
                                    payment_method VARCHAR(255),
                                    id_user        BIGINT
        );

        ALTER TABLE tb_payment
            ADD CONSTRAINT FK_TB_PAYMENT_ON_ID_USER FOREIGN KEY (id_user) REFERENCES tb_user (id_user);
    END IF;
END $$;