CREATE TABLE tb_payment
(
    id_payment   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255),
    payment_date TIMESTAMP WITHOUT TIME ZONE,
    value        DECIMAL,
    id_category  BIGINT,
    status       VARCHAR(255),
    CONSTRAINT pk_tb_payment PRIMARY KEY (id_payment)
);

ALTER TABLE tb_payment
    ADD CONSTRAINT FK_TB_PAYMENT_ON_ID_CATEGORY FOREIGN KEY (id_category) REFERENCES tb_category (id_category);